// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvmhGx2qrFk1Nc_7cK7aWLtrLkmn2IdJs',
    appId: '1:573217306084:web:c877843a37856fc02803f1',
    messagingSenderId: '573217306084',
    projectId: 'app-fixit-eba32',
    authDomain: 'app-fixit-eba32.firebaseapp.com',
    storageBucket: 'app-fixit-eba32.firebasestorage.app',
    measurementId: 'G-ES5ELYGXL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kwNfbyqR66zUjTQmfFOuui0c8UkZmso',
    appId: '1:573217306084:android:293387f9cdb2f7612803f1',
    messagingSenderId: '573217306084',
    projectId: 'app-fixit-eba32',
    storageBucket: 'app-fixit-eba32.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvmhGx2qrFk1Nc_7cK7aWLtrLkmn2IdJs',
    appId: '1:573217306084:web:c19eb019c9878cf22803f1',
    messagingSenderId: '573217306084',
    projectId: 'app-fixit-eba32',
    authDomain: 'app-fixit-eba32.firebaseapp.com',
    storageBucket: 'app-fixit-eba32.firebasestorage.app',
    measurementId: 'G-SC7V0H3DKV',
  );
}
